# -*- coding: utf-8 -*-

KNOWN_PLAYER_NICKS ={
##########
# HUMANS #
##########
'Alfonso':   ['akm'],
'Allan':     ['The_Cleaner',
              '-= Mr. ]v[urphy =-',
              '[BOT] Murphy',
              'Inmortal Endless',
              'Alex',
              'Makaveli',
              'Amazing',
              'Chance',],
'Carlos':    ['Carlos',
              'Trampas',
              'ANTI_Trampas',
              'Cypher'],
'Daniela':   ['D4n13l4'],
'Fernando':  ['Ferruiz',
              'Fernando',
              '\x0fFerruiz\x0f',
              'FerruiZ'],
'Jorge':     ['Jordude'],
'Kurt':      ['Trablas'],
'Marco':     ['\xcd\xc0rc0',
              'ÍÀrc0'],
'Nicolas':   ['SkyRyu',
              'Nmalbran',
              '^x01BSkyRyu^x02D^7',
              '^x01BSkyRyu^7',
              '^x0A1SkyRyu^7',
              '^x0A1SkyRyu^xB10\x95^7',
              '^x0A1\xd3ky\xd2yu^7',
              '^x0A1ÓkyÒyu^7',
              '\xd3ky\xd2yu'],
'Pedro':     ['pedratan'],
'Ricardo': ['riCOOLdator',
              'RiCOOLdator',
              'riCOOLdator\xf3',
              'riCOOLdator\x07-\x07JONAH\x07FALCON',
              'riCOOLdator\x07-\x07Long Dong Silver',
              'riCOOLdator\x07-\x07yo\x03SI\x03tengo\x03lentes\x03\x17',
              'RAKESH-dator - GIMME YOUR PASSPORTS FUCKING SLAVES!',
              'ricardator'],
'Francisco': ['[FS]Slaughter',],
'Unknown':   [''],

########
# BOTS #
########
'[BOT]Airhead':      ['[BOT]Airhead'],
'[BOT]Death':        ['[BOT]Death'],
'[BOT]Delirium':     ['[BOT]Delirium'],
'[BOT]Discovery':    ['[BOT]Discovery'],
'[BOT]Dominator':    ['[BOT]Dominator'],
'[BOT]Eureka':       ['[BOT]Eureka'],
'[BOT]Gator':        ['[BOT]Gator'],
'[BOT]Hellfire':     ['[BOT]Hellfire'],
'[BOT]Lion':         ['[BOT]Lion'],
'[BOT]Mystery':      ['[BOT]Mystery'],
'[BOT]Necrotic':     ['[BOT]Necrotic'],
'[BOT]Pegasus':      ['[BOT]Pegasus'],
'[BOT]Resurrection': ['[BOT]Resurrection'],
'[BOT]Scorcher':     ['[BOT]Scorcher'],
'[BOT]Sensible':     ['[BOT]Sensible'],
'[BOT]Shadow':       ['[BOT]Shadow'],
'[BOT]Shadow':       ['[BOT]Shadow'],
'[BOT]Thunderstorm': ['[BOT]Thunderstorm'],
'[BOT]Toxic':        ['[BOT]Toxic']
}
