# -*- coding: utf-8 -*-

PLAYERS ={

'Alfonso':   ['akm'],
'Allan':     ['The_Cleaner',
              '-= Mr. ]v[urphy =-',
              '[BOT] Murphy',
              'Inmortal Endless',
              'Alex',
              'Makaveli',
              'Amazing',
              'Chance',],
'Carlos':    ['Carlos',
              'Trampas',
              'ANTI_Trampas',
              'Cypher'],
'Daniela':   ['D4n13l4'],
'Fernando':  ['Ferruiz',
              'Fernando',
              '\x0fFerruiz\x0f',
              'FerruiZ'],
'Jorge':     ['Jordude'],
'Kurt':      ['Trablas'],
'Marco':     ['\xcd\xc0rc0',
              '?rc0',
              'ÍÀrc0'],
'Nicolas':   ['SkyRyu',
              'Nmalbran',
              '^x01BSkyRyu^x02D^7',
              '^x01BSkyRyu^7',
              '^x0A1SkyRyu^7',
              '^x0A1SkyRyu^xB10\x95^7',
              '^x0A1\xd3ky\xd2yu^7',
              '^x0A1ÓkyÒyu^7',
	      '\xc3\x93ky\xc3\x92yu',
              '\xd3ky\xd2yu'],
'Pedro':     ['pedratan'],
'Ricardo': ['riCOOLdator',
              'RiCOOLdator',
              'riCOOLdator\xf3',
              'riCOOLdator\x07-\x07JONAH\x07FALCON',
              'riCOOLdator\x07-\x07Long Dong Silver',
              'riCOOLdator\x07-\x07yo\x03SI\x03tengo\x03lentes\x03\x17',
              'RAKESH-dator - GIMME YOUR PASSPORTS FUCKING SLAVES!',
              'ricardator - de proporzionez cataztroficaz',
              'Pope\x01ricardator\x03THE\x1aSECOND\x1a:(',
              'ricardator'],
'Francisco': ['[FS]Slaughter',],
'Cristian':  ['Cchavez',],
'Almendra':  ['Almendra',
              '[InTerns]Almendra'],
'Diego':     ['[InTerns] Baka',
              'Baka'],
'Juan Pablo': ['JPablo',
               '[InTerns]JuanPablo'],
'Ignacio':   ['[InTerns]Nacho',
              'Nacho'],
'Isaias':    ['[InTerns]Demoxx'],
'Unknown':   [''],

}
